version: "4"

services:
  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    ports:
      - 9092:9092
    expose:
     - "9093"
    environment:
      - KAFKA_CFG_BROKER_ID=1001
      - KAFKA_CFG_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092,CONTROLLER://0.0.0.0:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      # - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CREATE_TOPICS=topic_test:1:1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
      - KAFKA_KRAFT_CLUSTER_ID=voz7tZIqRg6xVOxb1ef5Gw

    depends_on:
      - zookeeper
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      